[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  # Update this URL once you deploy your backend to Railway
  REACT_APP_API_URL = "https://badminton-injury-prediction-production.up.railway.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "functions" 